defaultSemverRangePrefix: ""

enableTelemetry: false

nodeLinker: pnp

packageExtensions:
  "@parcel/optimizer-image@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/transformer-image@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/transformer-js@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/types@*":
    dependencies:
      "@parcel/core": "*"
  "select2-bootstrap-5-theme@*":
    dependencies:
      "@popperjs/core": "*"
  "eslint-config-standard@*":
    dependencies:
      "eslint-plugin-n": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

supportedArchitectures:
  cpu:
    - "x64"
    - "arm64"
  os:
    - "darwin"
    - "linux"
    - "win32"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
