name: New Feature / Enhancement
description: Propose a new idea to be implemented
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to propose a new feature / enhancement idea.
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Include as much info as possible, including mockups / screenshots if available.
      placeholder: Description
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this request, you agree to follow our [Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)
          required: true
