# GITHUB ACTIONS - WORKFLOW

# Build the database dev docker image with the latest database dump every night
# so that developers don't have to manually build it themselves.

# DB dump becomes available at around 0700 UTC, so schedule is set to 0800 UTC
# to account for variations.

name: Nightly Dev DB Image

# Controls when the workflow will run
on:
  # Run every night
  schedule:
    - cron: '0 8 * * *'

  # Run on db.Dockerfile changes
  push:
    branches:
      - main
    paths:
      - 'docker/db.Dockerfile'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - platform: "linux/arm64"
            docker: "arm64"
          - platform: "linux/amd64"
            docker: "x64"
    steps:
      - uses: actions/checkout@v2
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build & Push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/db.Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: ghcr.io/ietf-tools/datatracker-db:latest-${{ matrix.docker }}
          
  combine:
    name: Create Docker Manifests
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v2
      
      - name: Get Current Date as Tag
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Create and Push Manifests
        run: |
          echo "Creating the manifests..."
          docker manifest create ghcr.io/ietf-tools/datatracker-db:nightly-${{ steps.date.outputs.date }} ghcr.io/ietf-tools/datatracker-db:latest-x64 ghcr.io/ietf-tools/datatracker-db:latest-arm64
          docker manifest create ghcr.io/ietf-tools/datatracker-db:latest ghcr.io/ietf-tools/datatracker-db:latest-x64 ghcr.io/ietf-tools/datatracker-db:latest-arm64
          echo "Pushing the manifests..."
          docker manifest push -p ghcr.io/ietf-tools/datatracker-db:nightly-${{ steps.date.outputs.date }}
          docker manifest push -p ghcr.io/ietf-tools/datatracker-db:latest
